# Docker Compose for DHIS2

services:

  db:
    container_name: db
    image: postgis/postgis:12-3.3
    env_file:
      - ./.env
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  dhis2:
    container_name: dhis2
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file:
      - ./.env
    volumes:
      - "fileResource:/opt/dhis2/files"
      - "logs:/opt/dhis2/logs"
      - "./credentials:/run/secrets/credentials"
    ports:
      # HTTP port removed to enforce HTTPS only
      - "9443:8443"
    depends_on:
      - db

  ingress:
    container_name: ingress
    build:
      context: ./ingress
      dockerfile: Dockerfile
    volumes:
      - "./shared:/usr/share/nginx/shared"
    ports:
      - "80:80"    # HTTP (redirects to HTTPS)
      - "443:443"  # HTTPS for DHIS2
      - "444:444"  # HTTPS for Adminer
      - "8000:8000" # HTTP file sharing (redirects to HTTPS)
      - "8443:8443" # HTTPS file sharing
    restart: unless-stopped

  init:
    container_name: init
    image: python:3.9-slim
    volumes:
      - "./src:/app"
    working_dir: /app
    command: >
      bash -c "apt-get update && apt-get install -y curl && 
      echo 'Waiting for DHIS2 to be ready...' && 
      until curl -k -s https://dhis2:443 > /dev/null; do 
        echo 'DHIS2 not ready yet, waiting 10 seconds...' && 
        sleep 10; 
      done && 
      echo 'DHIS2 is ready, proceeding with password change...' && 
      pip install -r requirements.txt && 
      python app.py && 
      chmod -R 777 /app && 
      echo 'Password change completed, stopping container...'"
    environment:
      - DHIS2_URL=https://dhis2:443
      - DHIS2_USERNAME=admin
      - DHIS2_PASSWORD=district
    depends_on:
      - dhis2
    restart: "no"

volumes:
  fileResource:
  logs:
  postgresql_data:
