# Docker Compose for DHIS2

services:

  db:
    container_name: db
    image: postgis/postgis:12-3.3
    env_file:
      - ./.env
    volumes:
      - "postgresql_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  dhis2:
    container_name: dhis2
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file:
      - ./.env
    volumes:
      - "fileResource:/opt/dhis2/files"
      - "logs:/opt/dhis2/logs"
      - "./credentials:/run/secrets/credentials"
    ports:
      # HTTP port removed to enforce HTTPS only
      - "9443:8443"
    depends_on:
      - db

  ingress:
    container_name: ingress
    build:
      context: ./ingress
      dockerfile: Dockerfile
    volumes:
      - "./shared:/usr/share/nginx/shared"
    ports:
      - "80:80"    # HTTP (redirects to HTTPS)
      - "443:443"  # HTTPS for DHIS2
      - "444:444"  # HTTPS for Adminer
      - "8000:8000" # HTTP file sharing (redirects to HTTPS)
      - "8443:8443" # HTTPS file sharing
    restart: unless-stopped

volumes:
  fileResource:
  logs:
  postgresql_data:
