x-dhis2-base: &dhis2-base
  image: dhis2-app
  build:
    context: .
    dockerfile: Dockerfile
  tty: true
  env_file:
    - ./.env
  environment:
    - DHIS2_DB_HOST=${DHIS2_DB_HOST}
    - DHIS2_DB_PORT=${DHIS2_DB_PORT}
    - DHIS2_DB_USER=${DHIS2_DB_USER}
    - DHIS2_DB_PASSWORD=${DHIS2_DB_PASSWORD}
    - DHIS2_DB_NAME=${DHIS2_DB_NAME}
  volumes:
    - "fileResource:/opt/dhis2/files"
    - "logs:/opt/dhis2/logs"
  networks:
    - dhis2-network

x-db-base: &db-base
  image: postgis/postgis:12-3.3
  volumes:
    - "postgresql_data:/var/lib/postgresql/data"
  environment:
    - POSTGRES_USER=${DHIS2_DB_USER}
    - POSTGRES_PASSWORD=${DHIS2_DB_PASSWORD}
    - POSTGRES_DB=${DHIS2_DB_NAME}

services:
  db:
    <<: *db-base
    networks:
      dhis2-network:
        aliases:
          - db
    ports:
      - "5432:5432"

  dhis2:
    <<: *dhis2-base
    ports:
      - "9443:8443"
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - dhis2-network

  ingress:
    image: dhis2-ingress
    build:
      context: ./ingress
      dockerfile: Dockerfile
    volumes:
      - "./shared:/usr/share/nginx/shared"
    ports:
      - "80:80"    # HTTP (redirects to HTTPS)
      - "443:443"  # HTTPS for DHIS2
      - "444:444"  # HTTPS for Adminer
      - "8000:8000" # HTTP file sharing (redirects to HTTPS)
      - "8443:8443" # HTTPS file sharing
    depends_on:
      - adminer
    networks:
      - dhis2-network

volumes:
  fileResource:
  logs:
  postgresql_data:

networks:
  dhis2-network:
    driver: bridge
